### ISSUE TITLE
DER and CER encoding not canonical

### ISSUE THREAD

**Issue by real-or-random** [etingof/pyasn1#11]
DER/CER encoding is supposed to be canonical, i.e., there is only one valid substrate for a value.

However:

```
>>> from pyasn1.type import univ
>>> from pyasn1.codec.der import der_encoder, der_decoder

>>> substrate1 = der_encoder.encode(univ.OctetString("long string"))
>>> substrate2 = der_encoder.encode(univ.OctetString("long string"), maxChunkSize=2)

>>> substrate1 != substrate2
True

>>> der_decoder.decode(substrate1)
(OctetString(b'long string', tagSet=TagSet((), Tag(tagClass=0, tagFormat=32, tagId=4))), b'')

>>> der_decoder.decode(substrate2)
(OctetString(b'long string', tagSet=TagSet((), Tag(tagClass=0, tagFormat=32, tagId=4))), b'')
```

The same happens with CER.

The problem here is that BER encoding actually forbids chunked strings, and CER exactly specifies when they are allowed. (See 9.2 and 10.2 in the X.690 spec)

**Comment by etingof** [comment]
Thank you for your report! And sorry for it has taken so long to address.

Most of the fixes I had in mind are in master (since 017f3adef2066242bf0bfa4015ddbebf952672ff). Though, I'm figured some more could be done to harden canonical codecs against non-canonical input. So I'm going to address these things, meanwhile I'd leave this issue open.

Anyway, if you are still at this, I'd appreciate your tests and feed back on the changes we have in place by now.

Thanks!

**Comment by real-or-random** [comment]
Thanks for the reply. I needed a canonical encoding for a project and there are not many standards.  I looked into ASN.1 but in the end I've choosen a strict variant of bencoding (https://github.com/acatton/flatbencode) because it's simpler.

So I don't have time to look into this further. But I think the standard explains mentions all the sources of ambiguity, so it should not be too hard to write tests.

**Comment by etingof** [comment]
With the latest changes in [the development branch[(https://github.com/etingof/pyasn1/tree/devel-0.4.1), I think this issue is hopefully gone:

```
>>> from pyasn1.codec.der import encoder as der_encoder
>>> from pyasn1.codec.der import decoder as der_decoder
>>> substrate1 = der_encoder.encode(univ.OctetString("long string"))
>>> substrate2 = der_encoder.encode(univ.OctetString("long string"), maxChunkSize=2)
>>> substrate1 != substrate2
False
```
Except that DER decoder is still forgiving towards non-canonical DER encoding:

```
>>> der_decoder.decode(substrate1)
(OctetString(b'long string', tagSet=TagSet((), Tag(tagClass=0, tagFormat=0, tagId=4))), b'')
>>> der_decoder.decode(substrate2)
(OctetString(b'long string', tagSet=TagSet((), Tag(tagClass=0, tagFormat=0, tagId=4))), b'')
>>> 
```
We can get the decoder rejecting non-canonical input as well if needed.
