### ISSUE TITLE
0.4.2 - optional univ.Null value is lost.

### ISSUE THREAD

**Issue by mingulov** [etingof/pyasn1#113]
It had been fixed on 0.3.7 with manually applied PR #92 , but since 0.4.2 the same problem returned back.

RFC 4210/4210 PKIMessage - PKIBody - CertReqMessages - CertReqMsg has an optional popo field which looses 'raVerified' univ.Null().subtype(...) value on encoding.

Example (just an empty PKIMessage for 'cr' with popo = raVerified):
`from pyasn1.type.char import IA5String`
`from pyasn1.type.univ import Integer, Null`
`from pyasn1.type.tag import TagSet, Tag`
`from pyasn1_modules.rfc4210 import PKIMessage, PKIHeader, PKIBody`
`from pyasn1_modules.rfc4211 import CertReqMsg, CertRequest, CertTemplate, ProofOfPossession`
`from pyasn1_modules.rfc2459 import GeneralName`
`from pyasn1.codec.der import encoder, decoder`

`header = PKIHeader()\`
`    .setComponentByPosition(0, 'cmp2000')\`
`    .setComponentByPosition(1, GeneralName().setComponentByPosition(1, IA5String('no@no', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))))\`
`    .setComponentByPosition(2, GeneralName().setComponentByPosition(1, IA5String('no@no', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))))`
`body = PKIBody()`
`crms = body.getComponentByName('cr')`
`crms.setComponentByPosition(0, CertReqMsg().setComponentByPosition(0, CertRequest().setComponentByPosition(0, Integer(0)).setComponentByPosition(1, CertTemplate())).setComponentByPosition(1, ProofOfPossession().setComponentByPosition(0, Null(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=0))))))`
`msg = PKIMessage().setComponentByPosition(0, header).setComponentByPosition(1, body)`
`print(msg.prettyPrint())`

`data = encoder.encode(msg)`
`structure, _ = decoder.decode(data, asn1Spec=PKIMessage())`
`print('Output')`
`print(structure.prettyPrint())`

Output for 0.3.7 with PR #92:
...
     certTemplate=CertTemplate:

    pop=ProofOfPossession:
     raVerified=

Output for 0.4.2:
...
     certTemplate=CertTemplate:

And that's all.

**Comment by etingof** [comment]
The problem here is that you are not initializing  the *raVerified* field because you are not passing any *value* to `Null` here:

    crms.setComponentByPosition(0, CertReqMsg().setComponentByPosition(0, CertRequest().setComponentByPosition(0, Integer(0)).setComponentByPosition(1, CertTemplate())).setComponentByPosition(1, ProofOfPossession().setComponentByPosition(0, Null(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=0))))))

Coupled with the fact that `ProofOfPossesion` is optional (see *popo* field), you do not get it encoded/decoded. So the fix is to pass `value=''` to Null:

    crms.setComponentByPosition(0, CertReqMsg().setComponentByPosition(0, CertRequest().setComponentByPosition(0, Integer(0)).setComponentByPosition(1, CertTemplate())).setComponentByPosition(1, ProofOfPossession().setComponentByPosition(0, Null(value='', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=0))))))

Previously, `Null` has a default value or empty string what always turned it into a value object. This was inconsistent with the rest of ASN.1 types so that has changed.

BTW, JFYI, the code above can be simplified a lot:

    crms[0]['certReq']['certReqId'] = 0
    crms[0]['certReq']['certTemplate']['popo']['reVerified'] = Null(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=0)))

**Comment by mingulov** [comment]
Thank you, yes it works fine on pyasn1 0.4.2 with valué='' for Null.

It is not a real code, just an example received by print(der), slightly changed as that received string had some errors during execution.
