### ISSUE TITLE
OpenType usage is not very clear

### ISSUE THREAD

**Issue by viraptor** [etingof/pyasn1#118]
I'd like to use the type from `rfc2459`, which includes an opentype. I've got a `AttributeTypeAndValue` from which I'd like to decode the value. The only way I know to do it currently is somewhat awkward.
```
value_bytes = part['value'].asOctets()
spec = part.getComponentType()['value'].openType[part['type']]
value = decoder.decode(value_bytes, asn1Spec=spec)[0]
```
I couldn't find any way documented. Is there one?

**Comment by etingof** [comment]
Ah, indeed!

You should just pass the `decodeOpenTypes=True` keyword parameter to main decode() function. It will automatically decode open types and replace `Any` fields with decoded structures.

I am going to document this shortly.

**Comment by etingof** [comment]
[Added](http://snmplabs.com/pyasn1/pyasn1/type/opentype/contents.html) some more docs and examples.

Sorry for it has taken so long!
