### ISSUE TITLE
I have asn data structure file and .dat file. How can i decode asn?

### ISSUE THREAD

**Issue by arsalan993** [etingof/pyasn1#119]
You have mentioned this
With pyasn1 you can build Python objects from ASN.1 data structures. For example, the following ASN.1 data structure:

Record ::= SEQUENCE {
  id        INTEGER,
  room  [0] INTEGER OPTIONAL,
  house [1] INTEGER DEFAULT 0
}
Could be expressed in pyasn1 like this:

"my question is , how can i generate code from a data structure"

**Comment by etingof** [comment]
Please use [asn1late](https://github.com/kimgr/asn1ate) for that.
