### ISSUE TITLE
ImportError: cannot import name opentype

### ISSUE THREAD

**Issue by sircybershark** [etingof/pyasn1#123]
Yo! I'm trying to leverage the Google Vision API to make a trash collecting robot... Any help with the error? This is the last step before my PiCam can recognize objects!!!

pi@dex:~ $ sudo su
root@dex:/home/pi# export
GOOGLE_APPLICATION_CREDENTIALS=vision1-ef4216c8c74c.json
root@dex:/home/pi# python camera-vision-logo.pyTraceback (most recent
call last):
  File "camera-vision-logo.py", line 52, in <module>
    main()
  File "camera-vision-logo.py", line 26, in main
    credentials = GoogleCredentials.get_application_default()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py",
line 1271, in get_application_default
    return GoogleCredentials._get_implicit_credentials()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py",
line 1256, in _get_implicit_credentials
    credentials = checker()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py",
line 1228, in _implicit_credentials_from_files
    credentials_filename)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py",
line 1414, in _get_application_default_credential_from_file
    from oauth2client import service_account
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py",
line 26, in <module>
    from oauth2client import crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py",
line 23, in <module>
    from oauth2client import _pure_python_crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_pure_python_crypt.py",
line 24, in <module>
    from pyasn1_modules.rfc2459 import Certificate
  File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py",
line 20, in <module>
    from pyasn1.type import opentype
ImportError: cannot import name opentype
root@dex:/home/pi#

**Comment by sircybershark** [comment]
Also, I tried the "pip install --upgrade pyasn1-modules" trick, but to no avail.. *sighs heavily*

**Comment by etingof** [comment]
This definitely has something to do with pyasn1/pyasn1-modules versions combinations. Which versions you currently use?

Try `pip install -U pyasn1 pyasn1-modules`

**Comment by sircybershark** [comment]
Okay so I just went to the root folder that has the pyasn1/pyasn1-modules and I guess the repo I downloaded has "pyasan 1, pyasan 1-0.4.2.dist.info, pyasan1_modules, and pyasan1_modules-0.2.1.dist-info" in it. Yet I tried the command you suggested, and it says the it "found existing installation: pyasn1 0.1.7"..?

**Comment by sircybershark** [comment]
Which combinations work best in your experience???

**Comment by sircybershark** [comment]
Okay, so I figured it out.. I can't edit my OS system apparently on my Pi...Ima have to take a different route. Thanks for all your help, sir. I really appreciate it<3 <3 <3
