### ISSUE TITLE
Various TagSet errors when decoding from custom Sequence objects

### ISSUE THREAD

**Issue by rkalz** [etingof/pyasn1#136]
So far, I've been using `der.decoder.decode` and building an OrderedDict with the desired keys manually. I tried writing my own Sequence objects and decoding directly into them, but I've been plagued with "tagset not in asn1Spec" errors.

For example, the bytes
`b'0=\xa0\x03\x02\x01\x17\xa26\x044\x07\x9eN\xdclLEe\x02,v\x12;\xdd\xdd\xdf\xf2\xb9x\x0f\xa3\x96\xfd\x98<\xab\xf1\x8a\xf9\x1bv\xed\x9a\x0e\x1e\xc7l\x87\x8c_\x8b\xf1\x17\x04\xfd\x17\x03\xb0\xe9-\x97\xc6'`
decode into
```
Sequence:
 field-0=23
 field-1=0x079e4edc6c4c4565022c76123bdddddff2b9780fa396fd983cabf18af91b76ed9a0e1ec76c878c5f8bf11704fd1703b0e92d97c6
```
as intended, correct typing and all, but when I try to decode it into the following sequence:
```
class EncryptedData(Sequence):
    componentType = NamedTypes(
        NamedType("etype", Integer()),
        OptionalNamedType("kvno", Integer()),
        NamedType("cipher", OctetString())
    )
```
I get the following error:
`pyasn1.error.PyAsn1Error: <TagSet object at 0x1d6a9414d68 tags 0:0:2-128:32:0> not in asn1Spec: <Integer schema object at 0x1d6a87ef908 tagSet <TagSet object at 0x1d6a8758b00 tags 0:0:2>>
`

Coukd you point out if this is a bug, or am I doing something wrong? Thanks

**Comment by rkalz** [comment]
I completely overlooked the fact that the spec I was referencing had implicit tags for each named type...

Man ASN.1 stinks...

**Comment by etingof** [comment]
Sorry for not taking a look at this earlier...

Generally, enabling debugging in pyasn1 helps spotting mismatching tags.
