### ISSUE TITLE
Build new release with fix for "BytesWarning pyasn1\codec\ber\decoder.py line 95"

### ISSUE THREAD

**Issue by sybrenstuvel** [etingof/pyasn1#14]
Hi,

I'm the author of the Python-RSA library. [One of my open tickets](https://github.com/sybrenstuvel/python-rsa/issues/80) is waiting for a release of PyASN1 that would close the ["BytesWarning pyasn1\codec\ber\decoder.py line 95"](https://sourceforge.net/p/pyasn1/discussion/324581/thread/45aadffe/) issue. The issue itself was closed 10 months ago, and the [last release on Pypi](https://pypi.python.org/pypi/pyasn1) is 16 months old, so I was wondering when you'll do another release to PyPi.

Cheers,
Sybren

**Comment by etingof** [comment]
I know I owe pyasn1 release for a long time already! But I hope to make a release before the first week of February.

Thanks for the heads up!

**Comment by etingof** [comment]
Release [0.2.1](https://github.com/etingof/pyasn1/releases/tag/v0.2.1) is out.

Many changes there, please file an issue if anything comes up. Thanks!
