### ISSUE TITLE
How to check the version with python code?

### ISSUE THREAD

**Issue by yjqiang** [etingof/pyasn1#147]
pyasn1.\_\_version\_\_  raise error. So pyasn1 does not follow https://www.python.org/dev/peps/pep-0396/

**Comment by etingof** [comment]
What kind of error? It's a bit of chicken-and-the-egg problem, but which pyasn1 version are you using?

The `__version__` attribute works for me:

```
>>> pyasn1.__version__
'0.4.5'
>>> 
```

**Comment by yjqiang** [comment]
I use pip to install pyasn1 and the latest version was 0.4.4. ?

**Comment by etingof** [comment]
Yes, `0.4.4` is the latest and it seems to have `__version__` in place:

```
$ python3 -m venv venv
$ . venv/bin/activate
(venv) $ pip install pyasn1
Collecting pyasn1
  Using cached https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl
Installing collected packages: pyasn1
Successfully installed pyasn1-0.4.4
(venv) $ python 
Python 3.5.4 (default, Oct  9 2017, 12:07:29) 
[GCC 6.4.1 20170727 (Red Hat 6.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyasn1
>>> pyasn1.__version__
'0.4.4'
>>> 
```

**Comment by yjqiang** [comment]
It is so strange, I used pythonista to run it. Several minutes age, I couldn't find __version__. Now it shows. Maybe it is a bug on pythonista.
