### ISSUE TITLE
Wrong constraint verification

### ISSUE THREAD

**Issue by kaxap** [etingof/pyasn1#153]
Getting error:

```
pyasn1.type.error.ValueConstraintError: <ValueSizeConstraint object at 0x7ff642e28e48 consts 128, 128> failed at: ValueConstraintError(b'51D389643EF12BB201912511824') at IMSCHARGE
```

But "51D389643EF12BB201912511824" is 28 byte long, not 128+

**Comment by etingof** [comment]
So the constraint seems to be to have this piece of data being equal to exactly 128 octets (or bits, depending on the data type perhaps).

Therefore this constraint violation error seems justified, no?

**Comment by kaxap** [comment]
In the ASN.1 Spec IMSCHARGE is 
```
IMSCHARGE                   ::= OCTET STRING(SIZE(128))
```

And it was compiled to 
```python
IMSCHARGE.subtypeSpec = constraint.ValueSizeConstraint(128, 128)
```

For example, in the same spec we have
```
IMEI ::= TBCD-STRING (SIZE (8))
```
which specifies an IMEI code which is not 8 bits (an IMEI has 15 digits + filler = 8 octets). Now it has been parsed correctly to 8 bytes, without raising a ValueConstraintError.

**Comment by etingof** [comment]
I am still confused... The IMSCHARGE field must be exactly 128 octets long, right? This is on the spec and in the code.

Now, you feed it a 28-octet long string and it fails because 28 != 128.

Could you please elaborate on where exactly the problem might be?

**Comment by kaxap** [comment]
> I am still confused... The IMSCHARGE field must be exactly 128 octets long, right?

Sorry for the confusion. You're absolutely correct. I was totally blinded by an assumption that Huawei hardware follows its own spec and overlooked the lower constraint. 

Much appreciate your help though.
