### ISSUE TITLE
No leading zeros when translated in hex string

### ISSUE THREAD

**Issue by flavienbwk** [etingof/pyasn1#157]
Hello,

I am trying to create a personalized RSA private key. The problem is that the library takes only decimals, but I want to add leading zeros to the final hexadecimal string (for the prime1 parameter).

Here is the part of the code :
```
seq = Sequence()
for x in [0, self.n, self.e, self.d, self.p, self.q, self.dP, self.dQ, self.qInv]:
    seq.setComponentByPosition(len(seq), Integer(x))
```

I would like to add leading zeros to the "p" parameter of my key.

How could I do that ?

Thanks.

**Comment by etingof** [comment]
Do you want these zeros in DER encoding?

Does it also makes sense from arithmetics standpoint? I imagine that whenever you have `p` participating in any sort of arithmetic operation, the leading zeros won't make any difference. 

I very well may be missing something. ;-)

**Comment by flavienbwk** [comment]
Thank you for your answer. Here is an example of the currently generated key, the "prime1" part : 

```
prime1:
    7f:40:dc:4c:5a:03:d1:53:42:f7:59:08:e0:aa:30:
    05:96:64:4a:dc:c4:68:5e:08:e2:8c:9d:d1:64:0c:
    2f:6e:e2:9a:b9:a2:39:82:4b:9e:bd:6b:76:ae:6d:
    87:21:a3:5e:9e:d9:8d:7e:a4:38:3e:59:09:34:a5:
    78:b5:f7:2e:89:5d:5c:37:52:ea:fd:f6:31:cc:ba:
    d2:d9:60:a6:45:1d:67:76:d2:1f:f4:9c:9d:c9:b1:
    90:45:51:ed:d2:7f:a6:b6:74:b4:99:7f:b1:0a:d9:
    b7:c2:be:8b:a4:07:22:0a:8e:3a:36:ff:6d:c1:1d:
    63:93:af:cb:4e:c0:47:9f:65:bf:df:e3:f0:5f:1e:
    98:61:45:74:ec:36:a7:a5:b1:f1:8d:3d:97:6b:5a:
    82:49:09:00:08:0d:9d:c2:74:a4:4e:30:a1:39:68:
    2f:22:34:71:13:aa:3b:f2:20:4f:8e:10:eb:d4:d0:
    9b:b5:8c:c2:53:5f:9d:71:13:0c:0f:21:b6:6e:13:
    39:40:d3:a6:b1:eb:74:ad:dd:0a:29:14:81:b1:90:
    ad:e0:53:f0:89:c8:00:fe:dc:ad:56:59:fc:28:1d:
    c0:cf:5e:08:c0:16:33:24:a3:52:bb:f3:25:10:43:
    c3:73:b8:40:4f:fc:6b:6b:77:bd:5f:22:24:eb:7f:
    15
```

I would like to have this "prime1", with the leading zeros : 
```
prime1:
    00:7f:40:dc:4c:5a:03:d1:53:42:f7:59:08:e0:aa:
    30:05:96:64:4a:dc:c4:68:5e:08:e2:8c:9d:d1:64:
    0c:2f:6e:e2:9a:b9:a2:39:82:4b:9e:bd:6b:76:ae:
    6d:87:21:a3:5e:9e:d9:8d:7e:a4:38:3e:59:09:34:
    a5:78:b5:f7:2e:89:5d:5c:37:52:ea:fd:f6:31:cc:
    ba:d2:d9:60:a6:45:1d:67:76:d2:1f:f4:9c:9d:c9:
    b1:90:45:51:ed:d2:7f:a6:b6:74:b4:99:7f:b1:0a:
    d9:b7:c2:be:8b:a4:07:22:0a:8e:3a:36:ff:6d:c1:
    1d:63:93:af:cb:4e:c0:47:9f:65:bf:df:e3:f0:5f:
    1e:98:61:45:74:ec:36:a7:a5:b1:f1:8d:3d:97:6b:
    5a:82:49:09:00:08:0d:9d:c2:74:a4:4e:30:a1:39:
    68:2f:22:34:71:13:aa:3b:f2:20:4f:8e:10:eb:d4:
    d0:9b:b5:8c:c2:53:5f:9d:71:13:0c:0f:21:b6:6e:
    13:39:40:d3:a6:b1:eb:74:ad:dd:0a:29:14:81:b1:
    90:ad:e0:53:f0:89:c8:00:fe:dc:ad:56:59:fc:28:
    1d:c0:cf:5e:08:c0:16:33:24:a3:52:bb:f3:25:10:
    43:c3:73:b8:40:4f:fc:6b:6b:77:bd:5f:22:24:eb:
    7f:15
```

Is it possible ?

**Comment by etingof** [comment]
Not out of the box.

But if you subclass [Integer type](https://github.com/etingof/pyasn1/blob/master/pyasn1/type/univ.py#L34), use it for `p` definition, subclass [Integer encoder](https://github.com/etingof/pyasn1/blob/master/pyasn1/codec/ber/encoder.py#L157), prepend some zeros [to the encoded value](https://github.com/etingof/pyasn1/blob/master/pyasn1/codec/ber/encoder.py#L174), then register your new type and encoder [here](https://github.com/etingof/pyasn1/blob/master/pyasn1/codec/ber/encoder.py#L675),that should hopefully make it...

The above steps essentially introduce new type and encoder.

**Comment by flavienbwk** [comment]
I confirm that leading zeros have **no impact** on the calculations.
Leading zeros are used only for security reasons (so each parameter have the same number of elements).

Thank you for your answer @etingof.
