### ISSUE TITLE
GeneralizedTime does not support UTC encoding to DER with 3 milliseconds digits

### ISSUE THREAD

**Issue by consp** [etingof/pyasn1#163]
The GeneralizedTime encoding does not support either UTC mode (with a 'Z')  if the microseconds are present and raises an error if the datetime results in more than 2 millisecond digits (e.g. xxxxxx12.345Z). Extending the maxlength field of the GeneralizedTimeEncoder to 20 or changing the compare operator to <= allows for UTC time with milliseconds to be properly supported. 

To replicate:
```python
from pyasn1.type.useful import GeneralizedTime
from datetime import datetime
from pyasn1.code.der import encode


encoder.encode(GeneralizedTime.fromDateTime(datetime(year=2019,month=1,day=1,hour=1,minute=1,second=1,microsecond=1)))
encoder.encode(GeneralizedTime.fromDateTime(datetime(year=2019,month=1,day=1,hour=1,minute=1,second=1,microsecond=123456)))

```

First result:
```python
b'\x18\x1120190101010101.0Z'
```
Second:
```python
raise error.PyAsn1Error('Length constraint violated: %r' % value)
pyasn1.error.PyAsn1Error: Length constraint violated: <GeneralizedTime value object at 0x0 tagSet <TagSet object at 0x0 tags 0:0:24> encoding us-ascii payload [20190101010101.900Z]>

```

Can be altered by either changing in https://github.com/etingof/pyasn1/blob/66d329acaaf204eff63ae595fd7d6f56cd530c72/pyasn1/codec/cer/encoder.py#L75
```python
    maxLength = 20
```
or by changing the compare operator to <=
https://github.com/etingof/pyasn1/blob/66d329acaaf204eff63ae595fd7d6f56cd530c72/pyasn1/codec/cer/encoder.py#L54
```python
if not self.minLength < len(octets) <= self.maxLength:
```
and 
https://github.com/etingof/pyasn1/blob/66d329acaaf204eff63ae595fd7d6f56cd530c72/pyasn1/codec/cer/encoder.py#L80
```python
    maxLength = 13
```

While most certificates require either UTCTime (till 2050) or GeneralizedTime without seconds (rfc 5280 and updates), some implementations require 3 digit millisecond comparability (e.g. timestamping protocols) which is now strangely only supports 2.

**Comment by etingof** [comment]
Thank you for raising this!

Hopefully, https://github.com/etingof/pyasn1/pull/164 fixes the problem. Your insights are very welcome!
