### ISSUE TITLE
Attempted operation on ASN.1 schema object

### ISSUE THREAD

**Issue by johndoe31415** [etingof/pyasn1#189]
Hi,

first off, thanks for creating pyasn1, it's tremendously helpful. I'm implementing X.509 certificate parsing and rely heavily on pyasn1 and pyasn1_modules, specifically RFC5280. I'm using pyasn1 0.4.7. Recently, I've run into an issue. I've created a minimal working example to illustrate it, copying from pyasn1_modules the definitions (so that it's a self-contained example). Here's the code:

```
import pyasn1.codec.der.decoder
from pyasn1.type import univ, namedtype, char, constraint
from pyasn1_modules import rfc5280

class DisplayText(univ.Choice):
    pass

DisplayText.componentType = namedtype.NamedTypes(
    namedtype.NamedType('ia5String', char.IA5String().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, 200))),
    namedtype.NamedType('visibleString',
                        char.VisibleString().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, 200))),
    namedtype.NamedType('bmpString', char.BMPString().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, 200))),
    namedtype.NamedType('utf8String', char.UTF8String().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, 200)))
)

class NoticeReference(univ.Sequence):
    pass

NoticeReference.componentType = namedtype.NamedTypes(
    namedtype.NamedType('organization', DisplayText()),
    namedtype.NamedType('noticeNumbers', univ.SequenceOf(componentType=univ.Integer()))
)

class UserNotice(univ.Sequence):
    pass

UserNotice.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('noticeRef', NoticeReference()),
    namedtype.OptionalNamedType('explicitText', DisplayText())
)

data = bytes.fromhex("30819e0c819b54686973204365727469666963617465206d6179206f6e6c792062652072656c6965642075706f6e2062792052656c79696e67205061727469657320616e64206f6e6c7920696e206163636f7264616e636520776974682074686520436572746966696361746520506f6c69637920666f756e642061742068747470733a2f2f6c657473656e63727970742e6f72672f7265706f7369746f72792f")
(asn1, tail) = pyasn1.codec.der.decoder.decode(data, asn1Spec = UserNotice())
nr = asn1.getComponentByName("noticeRef", instantiate = False)
print(type(nr))
#print(nr)
#print(nr.hasValue())
#print(nr.isValue)
```

The output of this is

```
<class 'pyasn1.type.base.NoValue'>
```

However, any of the commented out examples below fail, e.g.:

```
[...]
  File "/home/joe/.local/lib/python3.7/site-packages/pyasn1/type/base.py", line 236, in __getattr__
    raise error.PyAsn1Error('Attempted "%s" operation on ASN.1 schema object' % attr)
pyasn1.error.PyAsn1Error: Attempted "hasValue" operation on ASN.1 schema object
```

I find this behavior a bit surprising and am leaning towards seeing this as a bug. Isn't hasValue() explicitly meant to be able to make me distinguish between a schema and and actual instantiation?

As a workaround I can compare type(nr) to NoValue of course, or use isinstance(nr, NoValue) -- is this the recommended approach instead? Or is hasValue() the proper way to identify if an optional Sequence member has been included?

Note that when working with an easier example, everything behaves as expected:

```
x1 = univ.Integer()
print(x1.hasValue())
x2 = univ.Integer(123)
print(x2.hasValue())
```

prints

```
False
True
```

I.e., even though x1 clearly is only a schema, the .hasValue() method still works.

It'd be great if you could advise me if I'm doing something wrong here and, if so, if you could give me a pointer as to what the proper way is to determine if an optional sequence member has been included in the encoded data.

Thanks and best regards,
Johannes

**Comment by russhousley** [comment]
In you example, print(asn1.prettyPrint()) gives:

UserNotice:
 explicitText=DisplayText:
  utf8String=This Certificate may only be relied upon by Relying Parties and only in accordance with the Certificate Policy found at https://letsencrypt.org/repository/

This is correct; the optional 'noticeRef' field is absent in your data.

The dumpasn1 tool shows the same:

  0 158: SEQUENCE {
  3 155:   UTF8String
       :     'This Certificate may only be relied upon by Rely'
       :     'ing Parties and only in accordance with the Cert'
       :     'ificate Policy found at https://letsencrypt.org/'
       :     'repository/'
       :   }

**Comment by johndoe31415** [comment]
Hi Russ, that is correct, but that was not what the question was about. In fact, I am well aware that the noticeRef field is absent in the data. That is exactly the point; the question is how the code should look to discover programmatically if the absent field is absent or present. In particular, neither of the aforementioned examples -- the .isValue property or the .hasValue() method -- work; both throw an exception. With the more simple example I gave, this is not the case and I'm able to infer wether or not the "OPTIONAL" field is set. I was wondering what the correct way to determine if an optional structure member is set is.

**Comment by russhousley** [comment]
Sorry.  I clearly misunderstood your question.

I hope this helps...

>>> print(asn1['noticeRef'].hasValue())
False
>>> print(asn1['explicitText'].hasValue())
True
>>>

**Comment by johndoe31415** [comment]
Hey Russ! Huh, how about that! I can confirm this works for me. I had seen some strange effect where using the __getitem__ operator on the ASN.1 object would somehow instanciate the object (albeit with empty content), which I believe was why I used the getComponentByName kludge together with instantiate = False. It's a bit hazy in my mind now since it's been around 6 months, so I'm not exactly sure what my train of thought was.

In any case, I guess problem solved? Thanks for letting me know, I'm closing this issue.
