### ISSUE TITLE
Default encoding of OctetString

### ISSUE THREAD

**Issue by the-useless-one** [etingof/pyasn1#194]
Hi!

The default defined encoding of a `univ.OctetString` seems to be ISO-8859-1 (see the code [here](https://github.com/etingof/pyasn1/blob/master/pyasn1/type/univ.py#L795)). I was wondering why this choice was made, instead of something more universal, like UTF8?

This default encoding is causing some weird behavior in some programs relying on this library (see [here](https://github.com/SecureAuthCorp/impacket/pull/832) or [here](https://github.com/the-useless-one/pywerview/pull/34#issuecomment-567888292)).

Is it possible to change the default encoding to UTF8? If not, why not, and what do you suggest we can do to ensure proper encoding in our programs?

Thanks!

Y

**Comment by the-useless-one** [comment]
Up, any info regarding this issue? Thanks!

**Comment by the-useless-one** [comment]
Up, anything I can do to help resolve this issue? Right now, I'm not able to port my project to Python 3. Thanks!

**Comment by NetworkJack2** [comment]
Hi, this is actually important because pyasn1 is buried in the dep chain for CrackMapExec, which in turn needs pywerview.

There are a whole bunch of people that depend on this to work as expected.

It should be noted, UTF-8 is the now favored internationalization standard. Please switch to this.

**Comment by the-useless-one** [comment]
Up, has anyone any news on this project? There seems to have been no commit since march, and @etingof does not seem to be active anymore on Github, or other websites, such as StackOverflow, and such. I hope everything's okay.

Kind regards,

Y

**Comment by NetworkJack2** [comment]
Prime example of the "joys" of working with Free software sometimes.

**Comment by the-useless-one** [comment]
@GIJack, I can understand the frustration of not getting any response, but please keep in mind that open source developers have other concerns outside of their projects, especially during this dumpster fire of a year.

**Comment by the-useless-one** [comment]
After re-reading LDAP RFCs (thanks @ThePirateWhoSmellsOfSunflowers), we reached the conclusion that the problem may not come from `pyasn1`. We managed to fix our problem another way, so I'm closing this issue.

We wish @etingof a speedy recovery, and good health!
