### ISSUE TITLE
Is pyasn1 v0.4.8 is compatible with python3.11

### ISSUE THREAD

**Issue by vivek-crest** [etingof/pyasn1#220]
The [Pypi documentation](https://pypi.org/project/pyasn1/) mentions that pyasn1 v0.4.8 is compatible with Python 3.
Does this claim that the library is compatible with Python 3.11.x as well?
If not, is there a plan to release a Python 3.11.x compatible version?

**Comment by lextm** [comment]
Questions about that should now post to the new organization https://github.com/pyasn1/pyasn1/issues. This repo is no longer monitored by any maintainers.

Read #217 for more details.

**Comment by vivek-crest** [comment]
Thanks @lextm.  I have posted [here](https://github.com/pyasn1/pyasn1/issues/26).
