### ISSUE TITLE
pyasn1.error.PyAsn1Error: Read 100 bytes instead of expected 92

### ISSUE THREAD

**Issue by chetanpandey1266** [etingof/pyasn1#223]
Hi 
I am using pyasn1 to convert ber bytes to asn1. I saved the bytes in a txt file and then I am reading it and then passing it to `pyasn1.codec.ber.decoder.decode`. But I am getting this error. 

I read the decoder while where it was pointing to and this error is because `bytesRead != length`. So how could I make it work?

**Comment by lextm** [comment]
https://github.com/pyasn1/pyasn1/issues

You need to post to the new place.

**Comment by chetanpandey1266** [comment]
Okay
