### ISSUE TITLE
Missing doc/source/conf.py in pyasn1-0.2.3.tar.gz hosted by pypi

### ISSUE THREAD

**Issue by zmedico** [etingof/pyasn1#35]
When trying to build the documentation using the source from pypi's pyasn1-0.2.3.tar.gz, it fails as follows because `doc/source/conf.py` is missing from the tarball: 
```
$ python ./setup.py build_sphinx
running build_sphinx
creating ~/pyasn1-0.2.3/build
creating ~/pyasn1-0.2.3/build/sphinx
creating ~/pyasn1-0.2.3/build/sphinx/doctrees
creating ~/pyasn1-0.2.3/build/sphinx/html
Running Sphinx v1.3.1
error: [Errno 2] No such file or directory: 'conf.py'
```
Will you include `doc/source/conf.py` in the future? Thanks!

**Comment by etingof** [comment]
Thank you for raising this issue!

Missing config added in c6dec14638d656fe136da3109f4a9478831b03eb
