### ISSUE TITLE
0.2.4 release is missing

### ISSUE THREAD

**Issue by MuxZeroNet** [etingof/pyasn1#36]
Hello!

According to the [CHANGELOG](https://github.com/etingof/pyasn1/blob/master/CHANGES.rst#revision-024-released-xx-03-2017), there is a v0.2.4 release. I suppose it has been out, but it cannot be found in the [releases](https://github.com/etingof/pyasn1/releases) tab.

**Comment by etingof** [comment]
No, it's in current master, but it is not on PyPI yet.

**Comment by prometheanfire** [comment]
when is it planned to be in pypi?

**Comment by etingof** [comment]
Hopefully, by the end of July. There are still some rough edges in the code.

**Comment by prometheanfire** [comment]
Not sure it's still going to be the end of july, but this is likely to not be included in the openstack pike release if not released in the next day or so.

**Comment by etingof** [comment]
I am planning on releasing current master as 0.3.1 tonight or tomorrow. Let me know if I can try it with specific packages to catch possible regressions sooner rather than later.

**Comment by prometheanfire** [comment]
I'll link you the requirements change when you  make the update available.  submitting a change to the networking-bgp project (primary consumer iirc) should do it from the openstack side.

**Comment by etingof** [comment]
Great, thank you! AFAIK Ironic also has it as a dependency.

**Comment by etingof** [comment]
The [0.3.1](https://pypi.python.org/pypi/pyasn1/0.3.1) is out.

**Comment by prometheanfire** [comment]
https://review.openstack.org/487543 is where we are updating both
