### ISSUE TITLE
0.2.3 backward compatibulity issue.

### ISSUE THREAD

**Issue by abhsob** [etingof/pyasn1#37]
Installed parmiko 2.1.1 using pip which downloaded pyasn1 version 0.2.3. Caused issues for pysnmp-4.3.2

pysnmp-4.3.2-py2.7/pysnmp/proto/api/v1.py", line 58, in setDefaults
    1, self._errorStatus, verifyConstraints=False
  File "/usr/lib/python2.6/site-packages/pyasn1/type/univ.py", line 2123, in setComponentByPosition
    raise error.PyAsn1Error('Component value is tag-incompatible: %r vs %r' % (value, componentType))
PyAsn1Error: Component value is tag-incompatible: Integer('noError', NamedValues(('noError', 0), ('tooBig', 1), ('noSuchName', 2), ('badValue', 3), ('readOnly', 4), ('genErr', 5), ('noAccess', 6), ('wrongType', 7), ('wrongLength', 8), ('wrongEncoding', 9), ('wrongValue', 10), ('noCreation', 11), ('inconsistentValue', 12), ('resourceUnavailable', 13), ('commitFailed', 14), ('undoFailed', 15), ('authorizationError', 16), ('notWritable', 17), ('inconsistentName', 18))) vs Integer(subtypeSpec=ConstraintsIntersection(ConstraintsIntersection(), ValueRangeConstraint(0, Integer(2147483647))))

Reverted pyasn1 to version 0.1.9 and the code works.

**Comment by etingof** [comment]
Thank you for using pyasn1!

This issue can be solved by upgrading to the latest pysnmp [4.3.5](https://pypi.python.org/pypi/pysnmp).

Can you upgrade? Why not if so?

**Comment by abhsob** [comment]
We will eventually upgrade to pysnmp 4.3.5. But currently we are in system testing for the module that uses pysnmp. So it will be a while before we can test with 4.3.5. For now, I will downgrade to pyasn1 version 0.1.9. So does it mean that 0.2.X versions are not backward compatible with 0.1.X versions?

**Comment by etingof** [comment]
Hmm, could you provide a minimal pysnmp reproducer?

There was a [whirlpool of changes to pyasn1](https://github.com/etingof/pyasn1/blob/master/CHANGES.rst#revision-023-released-25-02-2017) since 0.1.9 (mostly performance and usability related), though I can't immediately recognize the problem you are facing as being caused by a regression in pyasn1...

**Comment by etingof** [comment]
With pyasn1 0.3.1 is out, this issue seems to become irrelevant. Please reopen if you think otherwise!
