### ISSUE TITLE
BitString should be able to accept bytes/bytesarray

### ISSUE THREAD

**Issue by danni** [etingof/pyasn1#39]
The BitString type should accept `bytes` as one of its options. At the moment you have to convert to hex via `hexlify` before you can use bytes.

(It's possible this is an oversight from Python 2 support, and the assumption is you can cast from bytes to str freely?)

**Comment by etingof** [comment]
In fact, you can instantiate `BitString` from `bytes` (Py3) or `str` (Py2):

    >>> BitString.fromOctetString(b'\xde\xad\xbe\xef')
    BitString('11011110101011011011111011101111')

This method is accidentally not documented, let me fix that shortly. ;-)

**Comment by danni** [comment]
Oh that's great. Thanks.

**Comment by etingof** [comment]
Finally, [added]!(http://pyasn1.sourceforge.net/docs/type/univ/bitstring.html#pyasn1.type.univ.BitString.fromOctetString)
