### ISSUE TITLE
DER encoder doesn't sort SET by tags

### ISSUE THREAD

**Issue by Erant** [etingof/pyasn1#40]
The DER specification specifies that the contents of a SET must be ordered by their tags. This doesn't seem to be happening, the ordering is random.

**Comment by etingof** [comment]
Thank you for rising this issue!

Please try the fix at the [set-components-sorting](https://github.com/etingof/pyasn1/tree/set-components-sorting) branch and let me know if it works for you.

**Comment by etingof** [comment]
Merged to master. Please re-open this issue in case of any troubles.
