### ISSUE TITLE
0.3.1 regression - GeneralizedTime/UTCTime CER/DER codecs

### ISSUE THREAD

**Issue by hwine** [etingof/pyasn1#55]
I hadn't pinned my version of pyasn1 yet on a new project, and got surprised by fresh installs into docker images. 0.3.1 gives the error:
```
'Uninitialized ASN.1 value ("__nonzero__" attribute looked up)'
```
when invoked by a library originally from Google Code (see [this note](https://github.com/hwine/fx-sig-verify/blob/pyasn1_regression/src/fx_sig_verify/verify_sigs/README.md) for history). Some brief ``pdb`` work showed it related to ``GeneralizedTime()`` objects.

**STR:**
1. ``git clone -b pyasn1_regression https://github.com/hwine/fx-sig-verify
1. ``cd fx-sig-verify``
1. Setup and activate venv
    1. ``pip install -r requirements.txt`` # this will use pyasn1>=0.3.1
    1. ``pip install -e .``
1. Show issue
    1. ``fx-sig-verify tests/data/32bit.exe``  # throws exception
        ```
        $ pip freeze | grep pyasn1
        pyasn1==0.3.1
        $ fx-sig-verify tests/data/32bit.exe
        verbose 1 based on True
        Processing tests/data/32bit.exe
        Processing file of size 246056 (at 0)
        fail for tests/data/32bit.exe
        errors:
            failed to process local file tests/data/32bit.exe 'PyAsn1Error('Uninitialized ASN.1 value ("__nonzero__" attribute looked up)',)'
        ```
    1. ``pip install --upgrade pyasn1==0.2.3``  # rollback to working verision
    1. ``fx-sig-verify tests/data/32bit.exe``  # no exception
        ```
        $ pip freeze | grep pyasn1
        pyasn1==0.2.3
        $ fx-sig-verify tests/data/32bit.exe
        verbose 1 based on True
        Processing tests/data/32bit.exe
        Processing file of size 246056 (at 0)
        pass for tests/data/32bit.exe
        ```

**Comment by etingof** [comment]
Thank you for raising this!

Just a quick note that I'm looking into it and report back here shortly.

**Comment by etingof** [comment]
Fixed in https://github.com/hwine/fx-sig-verify/pull/1

**Comment by hwine** [comment]
Thanks much! A bit more context for future archeologists:
 - Nothing is wrong with pyasn1 0.3.1
 - The code I reported was written for pyasn1 version 0.1.x
 - @etingof graciously offered patches to upgrade my calling convention.
