### ISSUE TITLE
PyAsn1Error when decoding explicitly tagged subtypes

### ISSUE THREAD

**Issue by jfinkhaeuser** [etingof/pyasn1#70]
I've got a little wrapper library at https://github.com/jfinkhaeuser/bran that goes a little beyond the ASN.1 specs to providing a canonical presentation.

Since upgrading to pyasn1 0.3.x my builds fail, and I'm having a hard time figuring out what if anything I'm doing wrong.

Summarized, I do the following:
- Encode more complex types as sequences:
```python
    self.MAPPING = univ.Sequence(
      tagSet = univ.Sequence.tagSet.tagExplicitly(
        tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0x04)
      )
    )
```
- In the mapping case, it's actually a sequence of two item sequences, representing the key and value.
- When *decoding*, there's now a `PyAsn1Error` when the sequence end is reached. Previously iteration would just stop.

I can circumvent that by catching the error, but that might hide other issues. I can explicitly add the length of the sequence, but my understanding of ASN.1 is that this shouldn't be necessary.

The error is "Compontent type not defined".

Do you have any pointers for me?

**Comment by etingof** [comment]
Quick questions:

* Could you please try your code with the current GitHub master? There is a relevant fix there.
* Could you give me a simple reproducer so I could readily debug it?

Thanks!

**Comment by jfinkhaeuser** [comment]
Sure.
Master doesn't change anything. My code reduced to its minimum (more or less, the iterator is just how I use it) works like this:
```python
from pyasn1.type import univ, tag
from pyasn1.codec.der.encoder import encode
from pyasn1.codec.der.decoder import decode

LIST = univ.Sequence(
  tagSet = univ.Sequence.tagSet.tagExplicitly(
    tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0x03) 
  )
)

data = [42, 123]

encoded = LIST.clone()

# encode
for idx, item in enumerate(data):
  encoded.setComponentByPosition(idx, univ.Integer(item))

# Works
print(encoded.prettyPrint())
assert encoded.isSameTypeWith(LIST)

# decode
def seq_iter(seq):
  idx = 0
  while True:
    try:
      print("Trying idx", idx)
      item = int(encoded.getComponentByPosition(idx))  
      yield item
      idx += 1
    except IndexError:
      break

decoded = list(seq_iter(encoded))
print("result", decoded)
```
Output is:
```bash
Sequence:
 field-0=42
 field-1=123

Trying idx 0
Trying idx 1
Trying idx 2
Traceback (most recent call last):
  File "minimal.py", line 35, in <module>
    decoded = list(seq_iter(encoded))
  File "minimal.py", line 29, in seq_iter
    item = int(encoded.getComponentByPosition(idx))
  File "/home/jens/src/3rdparty/pyasn1/pyasn1/type/univ.py", line 2208, in getComponentByPosition
    self.setComponentByPosition(idx)
  File "/home/jens/src/3rdparty/pyasn1/pyasn1/type/univ.py", line 2264, in setComponentByPosition
    raise error.PyAsn1Error('Component type not defined')
pyasn1.error.PyAsn1Error: Component type not defined
```

Previously trying index 2 raised an IndexError, as one would expect, too.

**Comment by etingof** [comment]
So what has changed is that `IndexError` got replaced by `PyAsn1Error` which is a change in behaviour, but on the other hand seems more consistent with the other exceptions pyasn1 produces here and there...

But! The iterators you implemented, they are actually built into `Sequence` which duck-types Python `dict`. Here your code modified to leverage that:

```
from pyasn1.type import univ, tag


LIST = univ.Sequence(
  tagSet = univ.Sequence.tagSet.tagExplicitly(
    tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0x03) 
  )
)

data = [42, 123]

encoded = LIST.clone()

# encode
for idx, item in enumerate(data):
  encoded[idx] = univ.Integer(item)

# Works
print(encoded.prettyPrint())

assert encoded.isSameTypeWith(LIST)

# decode
decoded = list(encoded.values())

print("result", decoded)
```

So it produces:

```
Sequence:
 field-0=42
 field-1=123

result [Integer(42), Integer(123)]
```
Would it make sense for your library to leverage that?

As a side note, the ASN.1 EXPLICIT tag you mentioned does not seem to play a role in the code we discuss here. What we played with so far are just data structures as opposed to DER serialization where all the tagging appear. ;-)

**Comment by jfinkhaeuser** [comment]
Yes, I know these are just data structures. The DER encoding seems to work just fine, but I wanted to provide a minimal example. Seems that the transcoding itself is not at fault.

I'm fine with using the index operators, yes. I did not find them when I started using pyasn1 (0.2.x). Maybe you added them afterwards, or the documentation did not mention them?

Either way, it doesn't seem to resolve my issue. Let me dig a little deeper now and find out why not.

**Comment by jfinkhaeuser** [comment]
Ah, turns out to be an easy one:

```python
../3rdparty/pyasn1/pyasn1/type/univ.py:2063: in __getitem__
    return base.AbstractConstructedAsn1Item.__getitem__(self, idx)
../3rdparty/pyasn1/pyasn1/type/base.py:590: in __getitem__
    return self.getComponentByPosition(idx)
../3rdparty/pyasn1/pyasn1/type/univ.py:2208: in getComponentByPosition
    self.setComponentByPosition(idx)
```

Yes, if all you do is use getComponentByPosition and that function raises the PyAsn1Error, then of course it won't change.

**Comment by jfinkhaeuser** [comment]
So, we may disagree on this, but raising anything *but* `IndexError` when using `__getitem__` with an index that does not exist seems to me like a real bug. Yes, it's more consistent with other errors, but it's also not at all Pythonic.

WDYT?

**Comment by jfinkhaeuser** [comment]
Maybe the solution is for you to catch `PyAsn1Error` in `__getitem__` itself to raise `IndexError` instead. That way your internal code is more consistent, but `__getitem__` is Pythonic.

**Comment by jfinkhaeuser** [comment]
Actually, one last comment: `collections.Mapping` should probably raise `KeyError`, `collections.Sequence` should raise `IndexError`. So there might be more non-Pythonic behaviour here.

https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes

**Comment by etingof** [comment]
> Actually, one last comment: collections.Mapping should probably raise KeyError, collections.Sequence should raise IndexError. So there might be more non-Pythonic behaviour here.

Yes, that makes perfect sense to me!

Let me see if I could change that without much compatibility pain...

**Comment by etingof** [comment]
Here is [the fix](https://github.com/etingof/pyasn1/pull/73). Would you test it before I merge?

Thanks!

**Comment by etingof** [comment]
Merged.
