### ISSUE TITLE
DER encoding produces constructed form of encoding

### ISSUE THREAD

**Issue by fzonneveld** [etingof/pyasn1#74]
```python
from pyasn1.codec.der import encoder
from pyasn1.type import univ

o = univ.OctetString('\xaa' * 1001)
encoder.emcode(o)
```
Results in '$\x82\x03\xef\x04\x82\x03\xe8\xaa\xaa .. \xaa\x04\0x01\xaa'

According to X.690 $10.2 the constructed form of encoding should not be used for DER encoding.
Expected value would be: '\x04\x82\x03\xe9\xaa\xaa..\xaa'

**Comment by etingof** [comment]
Thank you for raising this! The fix is coming!

**Comment by fzonneveld** [comment]
Thanks for the quick response.

**Comment by etingof** [comment]
https://github.com/etingof/pyasn1/pull/75 should fix this. I'd appreciate if you could test that before I merge. ;-)

Thank you!

**Comment by fzonneveld** [comment]
Checked the #75 (commit 1183c6c) with the example described in issue #74
and I see the result is correct, not in constructed form of encoding
anymore.

Thank you!

**Comment by etingof** [comment]
Merged. Thank you!
