### ISSUE TITLE
PER

### ISSUE THREAD

**Issue by MMYusuf** [etingof/pyasn1#82]
Hi Ilya.
 
Thank you for your work! What do you think about PER coding? 

> The extremely compact PER encoding is expected to be introduced in the upcoming pyasn1 release. 

I wonder when this might be cuz I am currently working on a project that uses PER ..
 
Thank you,
Marwan

**Comment by etingof** [comment]
Hi Marwan,

Right, that is in my TODO list. I have a couple of things planned to be done in prior to PER. So let's hope I get some time for that by the end of this year.

Otherwise everyone is welcome to come up with a PR. ;-)

**Comment by MMYusuf** [comment]
Great, looking forward !
