### ISSUE TITLE
hasValue() is erroneous when member is optional and is a Sequence() (maybe with other types as well)

### ISSUE THREAD

**Issue by pantunes** [etingof/pyasn1#86]
Hello,

When running the code below, we get different results from the function hasValue():

```
from binascii import hexlify
from pyasn1.type import univ, namedtype
from pyasn1.codec.der import encoder, decoder

print ">>> Sample 1"

class Sample(univ.Sequence):
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('a', univ.Integer()),
        namedtype.OptionalNamedType('b', univ.Integer())
        )
s1 = Sample()
s1['a'] = univ.Integer(1)

print 'hasvalue s1=', s1['b'].hasValue()

e_s1 = encoder.encode(s1)
print hexlify(e_s1)
s2 = decoder.decode(e_s1, asn1Spec=Sample())[0]

e_s2 = encoder.encode(s2)
print hexlify(e_s2)

print 'hasvalue s2=', s2['b'].hasValue()

print ">>> Sample 2"

class Sample(univ.Sequence):
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('a', univ.Integer()),
        namedtype.OptionalNamedType('b', univ.Sequence())
        )
s1 = Sample()
s1['a'] = univ.Integer(1)

print 'hasvalue s1=', s1['b'].hasValue()

e_s1 = encoder.encode(s1)
print hexlify(e_s1)
s2 = decoder.decode(e_s1, asn1Spec=Sample())[0]

e_s2 = encoder.encode(s2)
print hexlify(e_s2)

print 'hasvalue s2=', s2['b'].hasValue()

```
**Returns:**
>>> Sample 1
hasvalue s1= False
3003020101
3003020101
hasvalue s2= False
>>> Sample 2
hasvalue s1= True
3003020101
3003020101
hasvalue s2= True

Could you please fix this?
Thanks in advance

**Comment by etingof** [comment]
Thank you for rising this!

Could you please elaborate - is it `hasvalue s1=True` what you think is wrong or is it just `hasvalue s2=True` or both in Sample 2?

For me to better understand the context -- what is your use-case and the ultimate goal?

The `hasvalue s1= True` is so because empty SEQUENCE is actually a valid data instance which you can operate on. On the other hand, I understand that you may want to test if the optional component is present or not...

**Comment by pantunes** [comment]
Hi Ilya,

I think the 2 samples show some inconsistency as in "Sample 2", we don't set the optional parameter univ.Sequence() with any value and when accessing it through the method hasValue() it returns True.

The same does not happen when the member is univ.Integer() as we don't set it and hasValue() returns False.

I think would be better to have the same behaviour for these two scenarios or other type that a member gets hasValue() True without being explicitly set.

The hashes of both scenarios are the same but hasValue() returns differently for both variables? Does it make sense?

Another point is that if a parameter, is optional and not set, should not return hasValue() True.

Let me know about your thoughts.

Thanks for your feedback!
PS - I hope i was clear, let me know.

**Comment by etingof** [comment]
Hi Paulo!

The thing is that the `.hasValue()` call answers the question "is this an ASN.1 schema object or a value object?". The latter can be used like normal Python value while schema is only good as a factory for creating value objects.

When you do:

```
print 'hasvalue s1=', s1['b'].hasValue()
```

You first instantiate the `b` component and then test it for being a ASN.1 schema or value object. In this case `b` (being a structure itself) may or may not be considered as a value object. The rules for that may get complicated when the `b` structure has optional or defaulted components. Optionals would keep `b` treated as a schema while defaulted components would turn `b` into a value object...

If the question you want to ask is "did I ever touch `b`?", may be we could introduce a direct method for that like:

```
print '"b" is absent in s1 = ', s1.getComponentByPosition('b', instantiate=False) is noValue
```

Or something along these lines? Would that make sense?

Although I am still not sure what is the exact problem you are trying to solve. ;-)

**Comment by etingof** [comment]
OK, here is [the experimental PR](https://github.com/etingof/pyasn1/pull/87) implementing the "no instantiate" feature:

```
class Sequence(univ.Sequence):
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('name', univ.OctetString('')),
        namedtype.OptionalNamedType('nick', univ.OctetString()),
    )

s = Sequence()

s.getComponentByName('nick', instantiate=False) # -> univ.noValue

s['nick'] = 'xxx'
s.getComponentByName('nick', instantiate=False) # -> 'xxx'

s.clear()
s.getComponentByName('nick', instantiate=False) # -> univ.noValue
```

Would it help?

**Comment by pantunes** [comment]
Hi Ilya,
I'm on holidays now, will come back to you in 1 week if you don't mind.
I have limited internet access.
Thanks a lot for your feedback.

**Comment by etingof** [comment]
I hope this is good enough solution so it's [merged](https://github.com/etingof/pyasn1/tree/devel-0.4.1).

You are welcome to reopen this or open a new issue in case of further problems/ideas. ;-)
