### ISSUE TITLE
pyasn1 0.3.7 encoding of optional univ.Null broken

### ISSUE THREAD

**Issue by Eierkopp** [etingof/pyasn1#89]
Hello,

I just ran across the following problems best illustrated by this code snippet:

    from pyasn1.type import univ, namedtype, tag
    from pyasn1.codec.ber import encoder

    class Flag(univ.Null):
        pass

    class TestSeq(univ.Sequence):
        pass

    TestSeq.tagSet = univ.Set.tagSet.tagImplicitly(tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 1))
    TestSeq.componentType = namedtype.NamedTypes(
        namedtype.OptionalNamedType('flag', Flag().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0)))
    )

    t = TestSeq()
    #t.setComponentByName("flag", '')

    print t.getComponentByPosition(0).isValue

    with open("/tmp/test.bin", "wb") as f:
        f.write(encoder.encode(t))

Since `univ.Null` has a defaultValue, isValue detection breaks for uninitialized components e.g. in SequenceEncoder. Therefore a `univ.Null` is included even if not initialized. Here is the `dumpasn1` output for the generated `/tmp/test.bin`:

    % dumpasn1 /tmp/test.bin
      0   2: [1] {
      2   0:   [0]
           :     Error: Object has zero length.
           :   }
    0 warnings, 1 error

Obviously the flag is included though not initialized. Removing the line `defaultValue = ''.encode()  # This is tightly constrained` from `univ.py` fixes this problem.

The second problem can be seen when uncommenting `t.setComponentByName("flag", '')` and switching from `ber` to `der` encoding or explicitly calling encode(t, ifNotEmpty=True). The line `if options.get('ifNotEmpty', False) and not substrate:` in ber/encoder.py` will than remove the `univ.Null` from the encoded data even if set.

    % dumpasn1 /tmp/test.bin
      0   0: [1]
           :   Error: Object has zero length.

0 warnings, 1 error.

Best regards,

Eierkopp

**Comment by etingof** [comment]
Thank you for reporting this!

PR https://github.com/etingof/pyasn1/issues/89 hopefully fixes these, though I'm thinking to implement this in a clearer way within the 0.4.1 release.

Let me know if you encounter any more issues with this.

**Comment by Eierkopp** [comment]
Thanks for the quick fix ...

... and many thanks for a great piece of software.

Best regards,

Eierkopp

**Comment by etingof** [comment]
I've hopefully fixed this problem in a better way in the upcoming release branch [devel-0.4.1](https://github.com/etingof/pyasn1/tree/devel-0.4.1).

I'd appreciate you testing your code with that branch. ;-)

**Comment by Eierkopp** [comment]
Briefly tested with my code and everything ran smoothly. But with der
encoding sorting of records in a sequence sometimes changed between
0.3.8 and 0.4.1. Here is a small code snipped to trigger this
behaviour:
# start of test codeimport pyasn1from pyasn1.type import univ,
namedtype, tagfrom pyasn1.codec.der import encoderimport os
class Flag(univ.Null):    pass
class C1(univ.Integer):    pass
class C2(univ.Integer):    pass
class Some_Choice(univ.Choice):    pass
Some_Choice.componentType =
namedtype.NamedTypes(    namedtype.NamedType('c1',
C1().subtype(implicitTag=tag.Tag(tag.tagClassContext,
tag.tagFormatSimple, 0))),    namedtype.NamedType('c2',
C2().subtype(implicitTag=tag.Tag(tag.tagClassContext,
tag.tagFormatSimple, 1))))
class TestSeq(univ.Set):    pass
TestSeq.tagSet =
univ.Set.tagSet.tagImplicitly(tag.Tag(tag.tagClassContext,
tag.tagFormatConstructed, 69))TestSeq.componentType =
namedtype.NamedTypes(    namedtype.OptionalNamedType('flag',
Flag().subtype(implicitTag=tag.Tag(tag.tagClassContext,
tag.tagFormatSimple, 1))),    namedtype.OptionalNamedType('someChoice',
Some_Choice().subtype(implicitTag=tag.Tag(tag.tagClassContext,
tag.tagFormatConstructed, 7))),)
t = TestSeq()t.setComponentByName("flag",
'')t.getComponentByName("someChoice").setComponentByName("c2", 2)
print pyasn1.__version__
with open("/tmp/test.bin", "wb") as f:    f.write(encoder.encode(t))
os.system("dumpasn1 /tmp/test.bin")# end of test code

Output for 0.3.8 and 0.4.1 is:
0 warnings, 1 error.0.3.8  0   7: [69] {  3   3:   [7] { 
5   1:     [1] 02       :     }  8   0:   [1]       :     Error: Object
has zero length.       :   }
0 warnings, 1 error.
0.4.1
  0   7: [69] {
  3   0:   [1]
       :     Error: Object has zero length.
  5   3:   [7] {
  7   1:     [1] 02
       :     }
       :   }

I don't even know, which one is correct.

Best regards,

Eierkopp

**Comment by Eierkopp** [comment]
Briefly tested with my code and everything ran smoothly. But with der
encoding sorting of records in a sequence sometimes changed between
0.3.8 and 0.4.1. Here is a small code snipped to trigger this
behaviour:
    import pyasn1
    from pyasn1.type import univ, namedtype, tag
    from pyasn1.codec.der import encoder
    import os

    class Flag(univ.Null):
        pass

    class C1(univ.Integer):
        pass

    class C2(univ.Integer):
        pass

    class Some_Choice(univ.Choice):
        pass

    Some_Choice.componentType = namedtype.NamedTypes(
        namedtype.NamedType('c1', C1().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
        namedtype.NamedType('c2', C2().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
    )

    class TestSeq(univ.Set):
        pass

    TestSeq.tagSet = univ.Set.tagSet.tagImplicitly(tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 69))
    TestSeq.componentType = namedtype.NamedTypes(
        namedtype.OptionalNamedType('flag', Flag().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
        namedtype.OptionalNamedType('someChoice', Some_Choice().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 7))),
    )

    t = TestSeq()
    t.setComponentByName("flag", '')
    t.getComponentByName("someChoice").setComponentByName("c2", 2)

    print pyasn1.__version__

    with open("/tmp/test.bin", "wb") as f:
        f.write(encoder.encode(t))

    os.system("dumpasn1 /tmp/test.bin")

Output for 0.3.8 and 0.4.1 is:

    0.3.8
      0   7: [69] {
      3   3:   [7] {
      5   1:     [1] 02
           :     }
      8   0:   [1]
           :     Error: Object has zero length.
           :   }

    0 warnings, 1 error.


    0.4.1
      0   7: [69] {
      3   0:   [1]
           :     Error: Object has zero length.
      5   3:   [7] {
      7   1:     [1] 02
           :     }
           :   }

    0 warnings, 1 error.



I don't even know, which one is correct.

Best regards,

Eierkopp

**Comment by etingof** [comment]
Well, 0.4.1 variant seems correct.

The rule is that with DER components of a SET should be ordered by their numeric tag value. But CHOICE has a special treatment:

* For untagged CHOICE, it's innermost chosen component tag should be taken
* For tagged CHOICE, its own tag should be taken without looking at its components

Since `someChoice` has tag 7 which is greater than `flag` 1 in `TestSeq`, `flag` should go first.

Trouble is that this tagged CHOICE case [is not really handled by encoder](https://github.com/etingof/pyasn1/blob/devel-0.4.1/pyasn1/codec/der/encoder.py#L30). So 0.4.1 ordering worked out right by accident (comparing tag 1 of `flag` with tag 1 of `someChoice.flag`). I'm going to fix that shortly.

**Comment by etingof** [comment]
The https://github.com/etingof/pyasn1/pull/93/files should make tagged CHOICE order stable.

I'm not sure how to best handle ordering of same-valued tags. I bet they are better to be stable at least.
