### ISSUE TITLE
BER encoding output not full

### ISSUE THREAD

**Issue by MMYusuf** [etingof/pyasn1#95]
Hi ,
I got this sequence that i am trying to ber encode , however the last element is not output from the encoder. I wonder what may be the reason for ber encoder to ignore this element !?

this is the prettyPrint of the object right before ber encoding:

>CBCINFOMSGREQRESULT:
>   cbccberequesthandle=4
>   cbccbestatuscode=0
>   messageclass=0
>   messagetext=Success
>   area=AREADATALIST:
>    coordinatesystem=<no value>
>    nrofcoordinatepair=<no value>
>    coordinatepair=SequenceOf:
> 
>   repetitioninterval=1
>   messageid=2
>   messageinfolist=MESSAGEINFOLIST:
>     nrofintervals=2
>     intervalinfo=SequenceOf:
>
>     INTERVALINFO:
>      updatenr=0
>      messagestatus=0
>      starttime=<no value>
>      endtime=<no value>
>      pagelist=PAGELISTDATA:
>       nrofpages=1
>       page=SequenceOf:
>        PAGEDATA:
>         pagecontents=0x0a
>         pagelength=1
> 
>     INTERVALINFO:
>      updatenr=1
>      messagestatus=0
>      starttime=<no value>
>      endtime=<no value>
>      pagelist=PAGELISTDATA:
>       nrofpages=1
>       page=SequenceOf:
>        PAGEDATA:
>         pagecontents=0x68656c6c6f20776f726c640a
>         pagelength=12

and this is the ber encoder output, you will notice that area element is removed since its value is none. the messageinfolist, however, has values but you can not find it in the output:

> b'`\x1a\xa4\x18\x81\x01\x04\x82\x01\x00\x83\x01\x00\x84\x07Success\x87\x01\x01\x88\x01\x02'

prettyPrint after ber decoding:

> CBCINFOMSGREQRESULT:
>  cbccberequesthandle=4
>  cbccbestatuscode=0
>  messageclass=0
>  messagetext=Success
>  repetitioninterval=1
>  messageid=2

and this is the pyasn1 sequence class :

```
class CBCINFOMSGREQRESULT(univ.Sequence):
    pass


CBCINFOMSGREQRESULT.tagSet = univ.Sequence.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatConstructed, 0))
CBCINFOMSGREQRESULT.componentType = namedtype.NamedTypes(
    namedtype.NamedType('cbccberequesthandle', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.NamedType('cbccbestatuscode', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('messageclass', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('messagetext', char.VisibleString().subtype(subtypeSpec=constraint.ValueSizeConstraint(0, 255)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('area', AREADATALIST().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('areaidlist', AREAIDLIST().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('repetitioninterval', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('messageid', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('datacodingscheme', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.OptionalNamedType('warningtype', univ.BitString().subtype(subtypeSpec=constraint.ValueSizeConstraint(16, 16)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.OptionalNamedType('messageinfolist', MESSAGEINFOLIST().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11)))
```

Thanks,

**Comment by etingof** [comment]
There was a bug [fixed lately](https://github.com/etingof/pyasn1/blob/devel-0.4.1/CHANGES.rst#revision-041-released-xx-10-2017) which may be relevant to this issue. Could you please try [the development branch](https://github.com/etingof/pyasn1/tree/devel-0.4.1) and report back if it helped.

If not, can you please give me a simple reproducer which would work our-of-the-box so I could debug this?

Thanks!

**Comment by MMYusuf** [comment]
thanks,
I tried the branch and i am still getting the same problem. I will try to make a simple producer.
One thing i noticed is that when the sub elements of it :
starttime=<no value>
endtime=<no value>
are set to values, I get the output fully. but if they are left None as they are now, I dont get the whole element in the output!
is it related to having empty sub elements inside that element?

**Comment by MMYusuf** [comment]
I figured it out . sorry for the inconvenience.
that sub elements are not optional. apparently, if one sub element is not a value the whole element is not encoded! so i changed them to optional and it working now

**Comment by etingof** [comment]
Glad that issue got resolved!
